import "./globals.css";
import type { Metadata, Viewport } from "next";
import { I18nProvider } from "@/i18n/I18nProvider";
import { SITE } from "@/lib/site";
import InitialLoader from "@/components/InitialLoader";

export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: `${SITE.brandFull} — 死ぬ時に後悔しない人生を`,
    template: `%s — ${SITE.brand}`,
  },
  description: SITE.description,
  applicationName: SITE.brand,
  authors: [{ name: SITE.brand }],
  creator: SITE.brand,
  publisher: SITE.brand,
  alternates: {
    canonical: "/",
    languages: { ja: "/", en: "/" },
  },
  openGraph: {
    type: "website",
    siteName: SITE.brand,
    title: `${SITE.brandFull} — 死ぬ時に後悔しない人生を`,
    description: SITE.description,
    url: SITE.url,
    locale: SITE.locale,
    alternateLocale: [SITE.alternateLocale],
    images: [
      {
        url: SITE.defaultOgImage,
        width: 1200,
        height: 630,
        alt: SITE.brandFull,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE.brandFull} — 死ぬ時に後悔しない人生を`,
    description: SITE.description,
    images: [SITE.defaultOgImage],
    creator: SITE.twitter,
  },
  // Icons are auto-generated by Next.js from src/app/{favicon.ico,icon.png,apple-icon.png}
  manifest: "/manifest.webmanifest",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
};

export const viewport: Viewport = {
  themeColor: "#0E1014",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Inter:wght@400;500;600;700;800;900&family=Noto+Sans+JP:wght@400;500;700&family=Noto+Serif+JP:wght@500;600;700&family=Caveat:wght@500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body data-screen-label="Furi LP">
        <InitialLoader />
        <I18nProvider>{children}</I18nProvider>
      </body>
    </html>
  );
}
